# Generated by Django 4.1.1 on 2022-09-22 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('presupuesto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nif', models.IntegerField(max_length=30)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido1', models.CharField(max_length=200)),
                ('apellido2', models.CharField(max_length=200)),
                ('codigo_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cobrandoEmpleados.departamentos')),
            ],
        ),
    ]
