# Generated by Django 4.1.1 on 2022-09-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrandoEmpleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='nif',
            field=models.CharField(max_length=30),
        ),
    ]
